### ISSUE TITLE
Add support for BOP

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/1.8.9-Realistic-Terrain-Generation#13]

**Comment by topisani** [comment]
included but untested

**Comment by topisani** [comment]
currently not working - i guess its not surprising, as i just fixed compilation errors in the 1.7 API

**Comment by whichonespink44** [comment]
Ok, so I've finally managed to get my 1.8 groove on and have been looking at this.

There seems to be a problem with the way we're assigning the static topBlock and fillerBlock variables in some of the surface classes. SurfaceBOPVolcano, for example, the top, filler, and mix blocks are NULL, so just need to figure out why & then that's one hurdle overcome. Maybe BOP changed the block ID strings for some of its blocks like it did with IDs.

Need to get NEI installed so I can dump all the blocks & items and have a look.

**Comment by topisani** [comment]
no NEI for 1.8.9, the BOPBlocks class is from the new API though, so that one should work...

**Comment by topisani** [comment]
IDEA has a debug button XD

**Comment by whichonespink44** [comment]
Had a look at new BOPBlocks but didn't seem to have all the blocks yet (maybe they removed some). Either way, I'll be on the scene shortly to get back into it.

And yes, gotta try out that debugger! :)

**Comment by topisani** [comment]
fixed in #21
