### ISSUE TITLE
Ocean monuments generating only on second itteration

### ISSUE THREAD

**Issue by topisani** [Team-RTG/1.8.9-Realistic-Terrain-Generation#18]
first time you load chunks that should have a monument, no parts of the structure has generated. Guardians still spawn, so it is somehow there. Then, if you leave and come back (further testing required as to what exactly that means) the structure will have generated. Occacionally only half of the structure has generated the second time, and you might need to leave and come back a third time to get all of it. This might be because only half of the chunks were unloaded, as said, further testing is required

**Comment by whichonespink44** [comment]
Fixed in 767cad5
