### ISSUE TITLE
Add support for Agricultural Revolution

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/1.8.9-Realistic-Terrain-Generation#24]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2501618-the-agricultural-revolution-ver-0-7-2-reinventing

**Comment by topisani** [comment]
Whats included in this? im guessing it doesnt need biometweaker voodoo, so its just adding the biomes? ima need a bit of guidance for this

**Comment by whichonespink44** [comment]
Cool, yeah I can give you a crash course in biome support... can also put something in the GitBook for reference.

It's basically just creating a biome config, realistic biome, terrain, and surface for all of the overworld biomes in the mod. I usually do an NEI dump to get the biome names and class names if they don't have an API. From there, it's basically choosing an existing biome that most closely resembles the one you're adding support for and then tweaking as necessary. The tweaking is a little complicated, but we can go through it at some point.

**Comment by whichonespink44** [comment]
This issue was moved to Team-RTG/Realistic-Terrain-Generation#780
