### ISSUE TITLE
Vines generating in midair near jungle trees

### ISSUE THREAD

**Issue by reuakcin** [Team-RTG/1.8.9-Realistic-Terrain-Generation#28]
![image](https://cloud.githubusercontent.com/assets/17535295/13382927/50af7fe6-de3d-11e5-83e3-444280fc320e.png)
Vines are generating on the opposite side of the block to the side they should be on.

**Comment by topisani** [comment]
Wow interesting... I had this issue, then fixed it, but maybe it turns out I didn't have it and by fixing it I created it... Or something like that.
 List of mods and forge version please?

**Comment by topisani** [comment]
ahh i forgot to push it! derp.
Got it now, its fixed in #31
