### ISSUE TITLE
snow layers for ice plains?

### ISSUE THREAD

**Issue by topisani** [Team-RTG/1.8.9-Realistic-Terrain-Generation#32]
Now that im at controversal topics, ima throw in another one.
I recently tried to use the snowHeightCalculator for ice plains biomes, and i think... well i think it sure looks interesting.
![2016-02-29_00 06 02](https://cloud.githubusercontent.com/assets/3133596/13411288/8eabd330-df3c-11e5-841f-3df3d0bb1bfd.png)
speeking of controversial, heres a screenshot with an icy village:
![2016-02-29_00 08 49](https://cloud.githubusercontent.com/assets/3133596/13411289/8eace004-df3c-11e5-8cf5-38ca02ce970e.png)
didnt manage to find any without single biome enabled, so they are a bit bare because of the lack of bome bleed.
Is this cool, or is it meh, not so much? im not really sure, what do you guys think?

**Comment by srs-bsns** [comment]
Looks good to me.

Personally though, I usually disable villages in cold/snowy biomes because they just seem out of place. Especially the crops, which aren't something that should be overriden for the sake of compatibility with mods that need them.

The addition of the Igloo in 1.9 might change things though.. I'm going to have to check that out.

**Comment by Zeno410** [comment]
I'm a little meh on ice villages - I'd like to see igloos with those materials. Northern European villages made from ice blocks don't look quite right. Srs is right that other aspects of villages (also their clothes) look really out of place in ice wastelands

**Comment by Zeno410** [comment]
Some biomes have "dune shape" code which would be mondo cool (pardon the pun) in ice wasteland. It does some now but it could be "dunier"

**Comment by topisani** [comment]
thats BOP cold desert

**Comment by topisani** [comment]
normal desert but snow layers - thats what gave me the idea to add it here too
And i think the village ting is moving out of RTG into an addon

**Comment by whichonespink44** [comment]
personally, i'd rather hijack one of the vanilla icy biomes and use the full dune version... but I don't think Ice Plains would be right... maybe Ice Mountains? although I kinda like the way those are at the moment? not convinced it's right for vanilla at all, but.... it's just soooo cool

**Comment by topisani** [comment]
theres normal ice plains, ice mountains, and ice plains spikes. Maybe ice plains could have the dunes with greatly reduced height, and spikes just has spikes in smaller clusters?

**Comment by srs-bsns** [comment]
Ice plains spikes is a mutated biome though, and is usually quite rare.. I don't even recall ever seeing it once when playing vanilla minecraft.

Who the hell even plays vanilla anymore? :o

**Comment by whichonespink44** [comment]
I can't play anything in survival if it doesnt have RTG... it's just too bland.

Ice Plains Spikes would be a good biome to hijack if it wasn't for the spikes being such a unique feature.... maybe we could have the snow dunes with the Ice Spikes on the flatter terrain?

**Comment by topisani** [comment]
what if we do very flat dunes on ice plains? i allways hated how the dirt shows on the edge, and the dunes is way better than normal noise to make it look like really dry snow.
Then we could add a bit of height to the dunes in ice spikes, and of cause the spikes

**Comment by whichonespink44** [comment]
I think I'd need to see a screenshot to know for sure... actually, the more I think about it, the more I think the full dune-based polar desert style doesn't really fit in vanilla. Wouldn't mind seeing a few different designs that involve snow layers though.

**Comment by topisani** [comment]
first option: actually the dune code, but very goddamn flat
![2016-03-01_01 34 24](https://cloud.githubusercontent.com/assets/3133596/13413823/d2bcb632-df4d-11e5-9096-043ebaa5663b.png)

**Comment by topisani** [comment]
maybe this is a bit more relevant
![2016-03-01_01 41 55](https://cloud.githubusercontent.com/assets/3133596/13413954/d00f746e-df4e-11e5-9141-6be66f05eee3.png)

**Comment by whichonespink44** [comment]
2nd one looks pretty cool

**Comment by topisani** [comment]
im trying to up it a bit more. maybe its possible to smooth it out at the river a bit

**Comment by topisani** [comment]
![2016-03-01_01 46 56](https://cloud.githubusercontent.com/assets/3133596/13414021/812a74ec-df4f-11e5-8378-31684ca1ecb5.png)
There's our dune like behaviour, i kinda like it even though it goes a bit tall maybe?

**Comment by topisani** [comment]
this is now in 0.0.3 (since #40 )

**Comment by Zeno410** [comment]
I gotta agree with Pink - vanilla Ice Plains isn't anything like a snow desert so this isn't right for Ice Plains.

**Comment by topisani** [comment]
ill tweak this a bit more now that i know _something_ about terrain generation. That last screenshot is definately too deserty, but i still like the idea of snow layers on ice plains.

**Comment by Zeno410** [comment]
FWIW I don't usually like the snow layering effect. I don't know why, but I don't. Maybe it's not having *any* full blocks visible. Dunes look nice in sand but in snow layers - bleh.

**Comment by whichonespink44** [comment]
I'm a huge fan of the snow layer dunes in the Snowy/Polar Desert template (just so visually unique), but again, I'm not convinced we should be adding the snow layers to any of the vanilla biomes.

However, since it's purely a surface thing, maybe we could add a config option for it if we can come up with a design that fits?

**Comment by topisani** [comment]
What about something like the flat part of this.
![ ](http://www.siddharthprem.com/Galleries/Lofoten/i-TP47Ph8/0/X2/IMG_1157_up-web-X2.jpg)
Base height will be 62 so it's a snow layer on top of the level where the ice is, and then it's completely flat except for the occasional 2 or 3 thick snow layer instead. That will recreate that image perfectly and I think it would be awesome

**Comment by Zeno410** [comment]
Oh, that would be fine, I think. I was thinking about something like that for the Glacier biome, actually, in the sense of off-and-on snow layers.
