### ISSUE TITLE
Mod support

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/1.8.9-Realistic-Terrain-Generation#4]
only support for buildcraft, BOP and thaumcraft is included. all of those are still untested

**Comment by topisani** [comment]
greatly reduced in #7

**Comment by whichonespink44** [comment]
Of all the mods that RTG 1.7.10 supports... how many have actually updated to 1.8?

**Comment by srs-bsns** [comment]
Biomes 'O Plenty (beta)
Buildcraft (alpha)
Thaumcraft (release)

Abyssalcraft has a 1.8.9 release, but RTG support for that is still in `dev` :)

**Comment by topisani** [comment]
It seems we can then change this to untested

**Comment by whichonespink44** [comment]
Cool, that means RTG will support all the 1.8 biome-adding mods from the get-go... nice!

I'll create separate issues for each mod, just so we can keep things nice and tidy.
