### ISSUE TITLE
Add Support for Beautiful Vanilla Mod-1.8.9

### ISSUE THREAD

**Issue by WenXin20** [Team-RTG/1.8.9-Realistic-Terrain-Generation#44]
V0.5 adds 2 new biomes.
http://minecraft.curseforge.com/projects/beautiful-vanilla-alpha-0-45-for-minecraft-1-8/files/2285873

**Comment by whichonespink44** [comment]
This issue was moved to Team-RTG/Realistic-Terrain-Generation#777
