### ISSUE TITLE
Mesa terrain

### ISSUE THREAD

**Issue by topisani** [Team-RTG/1.8.9-Realistic-Terrain-Generation#45]
Been working a bit on mesas:
Vanilla has a few variations.
Mesa, Mesa Plateau, Mesa Plateau M, Mesa Plateau F, Mesa Plateau M F, Mesa Bryce.
Yeah, a few. 

The plain old Mesa should in my oppinion just be a red desert (but without the dunes), with mixed in grass and coarse dirt, pretty much as it is some places currently.

The mesa plateau should be the tall flattop plateaus, that look a lot like vanilla versions.

Now, the interesting stuf: Mesa M:
![2016-03-07_15 17 15](https://cloud.githubusercontent.com/assets/3133596/13578523/c1b7398e-e498-11e5-984b-cfc64f0f14ad.png)
Im thinking slightly less noisy version of that.

The F variations should be like the originals, but with more trees, like they are in vanilla.

The bryce version should be like this: ![](https://upload.wikimedia.org/wikipedia/commons/6/64/BryceCanyon-Amphiteatre1.jpg)

**Comment by topisani** [comment]
![2016-03-07_21 18 58](https://cloud.githubusercontent.com/assets/3133596/13582062/4d2f41ee-e4aa-11e5-88b3-4de7b1a8ac4a.png)
Bryce candidate. Though it looks cool its too noisy. I was considering adding a check for nearby biomes, so it turns into looking more like the plateau when its closer to other biomes, but i also kinda like the bleeding over

**Comment by Zeno410** [comment]
Sadly as sub-biomes both Bryce and M will have the problem of being smoothed-out in most circumstances. Maybe we should look at some standard system for "editing" biomes. There's a technical issue in that the "thinking" about what would be a hills area, M area, etc, is done in the Terrain routines, and they don't have direct access to the biome arrays because the smoother gets in the way. But we could try something like having a "biome revision request" pile the Terrain routines add to and something like the surface routines draws from to actually change the biome.

**Comment by Zeno410** [comment]
For the Bryce you primarily want more octaves (noise functions with different wavelengths) rather than higher-amplitude noise. From my experience with Flying Mountains that Bryce looks VERY doable.

**Comment by topisani** [comment]
i am considering making the plain mesa biome a red desert. It would look good to always have a red desert around  the mesa plateaus. Any oppinions?

**Comment by whichonespink44** [comment]
Got any real-life examples of the end goal?

**Comment by Zeno410** [comment]
Doesn't vanilla do the plain Mesa as a red desert?  But I usually like the Mesa abutting other types of terrain.

I didn't say this clearly, but I was getting Bryce-style effects unintentionally in my Flying Mountains. I had three layers of terrain and a noise picking which one, with transition zones (so 1-0.7 top layer, 0.6-.0.7 blended transition from middle to top, 0.4-0.6 middle layer, etc.) I think if you had 5 layers and a complicated noise (lots of octaves) doing the picking, the Bryce effect would fall right out of it.

**Comment by topisani** [comment]
![2016-03-09_11 20 06](https://cloud.githubusercontent.com/assets/3133596/13641754/eceee020-e619-11e5-88b1-5ccaeed009ab.png)
thats mesa with desert terrain. I like it, maybe a bit lower dunes, or less dirt/grass, but i like the idea.
as for the bryce, this is where its currently at, it might need a bit more tweaking, maybe more flat tops, but i have recently made some progress in the plateau code, maybe i can apply that to this a bit better too. 
![2016-03-08_17 35 10](https://cloud.githubusercontent.com/assets/3133596/13641793/17f61b26-e61a-11e5-8fc5-2888830dda6a.png)

as for the plateaus themselves, this is their current state. Not quite happy with that one yet though.
![2016-03-09_11 34 37](https://cloud.githubusercontent.com/assets/3133596/13641855/6ca09de0-e61a-11e5-8998-400aff64e1aa.png)
and yes, i am working on noisy stripes.

Last one, the Mesa Plateau F:
![2016-03-09_11 21 43](https://cloud.githubusercontent.com/assets/3133596/13641879/843ca17e-e61a-11e5-8237-715e0661ed98.png)
Might add occacional actual forrests on top of those.

**Comment by whichonespink44** [comment]
Not completely sold on the dune-based Mesa, but not totally against it.

Really liking the idea of a lot more biota on the top of the Mesa Plateau F.

**Comment by topisani** [comment]
That dune is definately too high for the mesa, the main thing is the red desert theme.

**Comment by whichonespink44** [comment]
Red desert Mesa works for me.

**Comment by Zeno410** [comment]
The dune mesa is good for resembling the vanilla, except the vanilla has no biota. Maybe fewer shrubs? A few is good to make it a playable start (some wood). There are scattered full trees on the vanilla Mesa Plateau F so that's a good target there.

**Comment by topisani** [comment]
![2016-03-12_11 07 13](https://cloud.githubusercontent.com/assets/3133596/13722354/d95ac30a-e842-11e5-8643-ab7c014c4457.png)
I dont know anything about decorations, so it has no trees. But theres now grass patches to grow them on. I was thinking plain vanilla oak trees, but maybe we could design something new?

**Comment by whichonespink44** [comment]
Those slopes leading up to the steeper cliffs are absolutely lovely. Is that Mesa Plateau F?

I'm cool with coming up with a new tree if we can find one that fits... maybe some kind of dead tree?

![](https://tcproduction.blob.core.windows.net/media/%7B6cae855e-9ba7-4eb2-956f-dfeb85eeca5f%7D.http--www.blacktomato.co.uk-wp-content-uploads-2009-10-flinders-ranges-tree.jpg)

![](http://pre11.deviantart.net/f4fd/th/pre/i/2013/176/7/d/dead_tree_pack_001___hb593200_by_hb593200-d6aktb9.png)

Having said that, tree development is a pretty deep rabbit hole and we should probably concentrate on the terrain/surface/decoration systems before getting into new trees.

**Comment by topisani** [comment]
the one with sand/grass on top is the F version. The normal Plateau is the one in the background with the clay on top. And that lovely slope is biomesmoothening. I think.

**Comment by Zeno410** [comment]
Trees are definitely a rabbit hole, and also something we can put off. Changing terrain creates chunk walls; changing trees is generally doable in an existing world as long as the differences aren't too drastic.
