### ISSUE TITLE
Village materials

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/1.8.9-Realistic-Terrain-Generation#5]
all villages are made of oak and stone

![](https://cloud.githubusercontent.com/assets/3133596/13179375/ef29bf36-d723-11e5-84fa-1cb6449573a6.png)

**Comment by topisani** [comment]
What are your stands on biomes specific villages for other than desert? as in acacia wood in savannas etc? we could add some villagematerial options for biomes - stair1 stair2 roads walls and fences?

**Comment by whichonespink44** [comment]
Yeah, this is within RTG's scope, as long as it at least has an option to 'get out of the way' if other mods try to do the same thing.

This is actually a feature request for 1.7.10 as well. The basic system is in place to be able to do it (see [EventManager](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/master/src/main/java/rtg/event/EventManagerRTG.java#L183-L263) ), so it's just a case of adding the necessary defaults to the biome config system, although I think village options should probably go into their own config file, so either:

/config/RTG/biomes/vanilla_villages.cfg

or

/config/RTG/biomes/villages/vanilla.cfg

as the biome-specific configs are already quite massive and will only get bigger as more options are added in the future.

**Comment by topisani** [comment]
ill do it for 1.8.9 then, and i may either backport it myself later or let one of you guys backport it if i dont get the time

**Comment by whichonespink44** [comment]
When we port from 1.7.10, will the commits come across as well? So like, if I re-decorate a biome in commit #XYZ, will that commit #XYZ get brought across into the 1.8.9 history?

**Comment by topisani** [comment]
yep - but that might be hard the other way around

**Comment by whichonespink44** [comment]
Yeah, there will likely be conflicts when merging a 1.8-ported feature from 1.7 back into 1.8 (guess we'll find out soon enough), but as long as we resolve the conflicts, it should be fine... I think.

**Comment by topisani** [comment]
The original issues is fixed, but not pulled from my repo. Its kinda pointless though as its all being replaced anyway
