### ISSUE TITLE
Crash on Server startup - java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by rckymtnrfc** [Team-RTG/1.8.9-Realistic-Terrain-Generation#52]
I'm seeing this with version 0.0.4.

http://pastebin.com/8hAZP9TG

Thanks!

**Comment by topisani** [comment]
Yeah sorry, i should've known those mesa changes were too experimental... I know exactly what's wrong,gimme a few hours. This crash is bound to happen eventually for anyone who finds a mesa biome

**Comment by topisani** [comment]
No actually it should be seed specific, so if you don't get it on world startup, you should be fine

**Comment by topisani** [comment]
Can you post your seed here too? For testing porpoises :)

**Comment by rckymtnrfc** [comment]
Seed: 437023385211883797

**Comment by topisani** [comment]
fixed in #53 and #54 and all  of that is in 0.0.5
