### ISSUE TITLE
Underground Gravel Generation?

### ISSUE THREAD

**Issue by MagnusRevang** [Team-RTG/1.8.9-Realistic-Terrain-Generation#65]
I kerp stumbling on pockets of air with a lot of exposed ore - some even floating, yet I never encounter gravel while underground? This leads me to believe that gravel fails to generate - is this the case? Mining in a mushroom island biome

**Comment by whichonespink44** [comment]
This issue was moved to Team-RTG/Realistic-Terrain-Generation#773
