### ISSUE TITLE
Biome Repair System issues

### ISSUE THREAD

**Issue by topisani** [Team-RTG/1.8.9-Realistic-Terrain-Generation#8]
![2016-02-20_19 30 06](https://cloud.githubusercontent.com/assets/3133596/13198441/0222d8a8-d809-11e5-84a2-4242ae6a38fd.png)
This ocacionally happens, i have no idea why. Is it in 1.7 as well?

**Comment by whichonespink44** [comment]
Cross-version duplicate of #456

**Comment by whichonespink44** [comment]
This issue was moved to Team-RTG/Realistic-Terrain-Generation#782
